Changed typings to use styles from react. Also changed how the class type was eported due to 'error TS2666: Exports and export assignments are not permitted in module augmentations.' errors. Not sure if this is best-pratice, but so far it seems good..